exclude: '^docs/conf.py|^tests/files/|^src/geno2phenotb/static/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows


# Sort imports
- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
  - id: isort

# Black formatter
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3
    args: ['-l 100', '--safe']

# Auto flake8
- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.0
  hooks:
  - id: autoflake

# Doc8 Test
- repo: https://github.com/PyCQA/doc8
  rev: v1.0.0
  hooks:
  - id: doc8

# Local tests with mypy, sphinx-spellcheck and sphinx-linkcheck
- repo: local
  hooks:
  - id: mypy
    name: mypy type check
    language: system
    entry: bash -c "mkdir -p .cache && mypy --install-types --non-interactive --cache-dir=.cache/ src/ tests/ setup.py"
  - id: sphinx-spelling-check
    name: Sphinx spelling check
    language: system
    entry: bash -c "cd docs/ && make spelling"
  - id: sphinx-linkcheck
    name: Sphinx link check
    language: system
    entry: bash -c "cd docs/ && make linkcheck"
