package:
  name: geno2phenotb
  version: "1.0.0"

source:
  path: .


build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python=3.7.15
    - pip
    - setuptools=65.5.0
  run:
    - bwa=0.7.17
    - gatk=3.8
    - imbalanced-learn=0.8.1
    - joblib=1.1.1
    - mtbseq=1.0.4
    - numpy=1.21.5
    - numpy-base=1.21.5
    - packaging=21.3
    - pandas=0.25.3
    - perl-base=2.23
    - python=3.7.15
    - samtools=1.6
    - scikit-learn=0.24.2
    - scipy=1.7.3
    - setuptools=65.5.0
    - importlib_metadata
    - wheel=0.37.1

test:
  imports:
    - geno2phenotb

about:
  home: https://github.com/msmdev/geno2phenoTB
  license: LGPL-3.0-only
