
name: tests

on:
  push:
    # Avoid using all the resources/limits available by checking only
    # relevant branches and tags. Other branches can be checked via PRs.
    branches: [main]
    tags: ['v[0-9]*', '[0-9]+.[0-9]+*']  # Match tags that resemble a version
  pull_request:  # Run in every PR
  workflow_dispatch:  # Allow manually triggering the workflow
  schedule:
    # Run roughly every 15 days at 02:00 UTC
    # (useful to check if updates on dependencies break the package)
    - cron: '2 0 1,16 * *'
  release:
    types: [published]

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre_commit_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.17
          cache: 'pip' # caching pip dependencies
          fetch-depth: 0  # deep clone for setuptools-scm
      - name: Run static analysis and format checkers
        run: |
          pip install -U pip setuptools -e ".[dev]"
          pipx run pre-commit run --all-files --show-diff-on-failure

  test:
    needs: [pre_commit_check]
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Activate conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          environment-file: tests/g2p-test.yaml
          python-version: 3.8.17
          activate-environment: g2p-test
      - name: Inspect conda environment
        shell: bash -el {0}
        run: |
          conda info
        # conda list
      - name: Run tests
        shell: bash -el {0}
        run: |
          pip install -e .
          python -m pytest
      - name: Generate coverage report
        run: pipx run coverage lcov -o coverage.lcov
      - name: Upload partial coverage report
        if: ${{ !env.ACT }} # skip during local actions testing
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: coverage.lcov
          github-token: ${{ secrets.github_token }}
          flag-name: ${{ matrix.platform }} - py${{ matrix.python }}
          parallel: true

  self_test:
    needs: [pre_commit_check]
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Activate conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          environment-file: tests/g2p-test.yaml
          python-version: 3.8.17
          activate-environment: g2p-test
      - name: Inspect conda environment
        shell: bash -el {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -el {0}
        run: |
          pip install -e .
          geno2phenotb test -f

  complete_run:
    needs: [pre_commit_check]
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Activate conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: tests/g2p-test.yaml
          python-version: 3.8.17
          activate-environment: g2p-test
      - name: Inspect conda environment
        shell: bash -el {0}
        run: |
          conda info
        # conda list
      - name: Run tests
        shell: bash -el {0}
        run: |
          pip install -e .
          geno2phenotb test -c

  finalize:
    if: ${{ !github.event.act }} # skip during local actions testing
    needs: [test, self_test]
    runs-on: ubuntu-latest
    steps:
      - name: Finalize coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  publish:
    needs: [finalize, complete_run]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          environment-file: tests/g2p-build.yaml
          python-version: 3.8.17
          activate-environment: g2p-build
      - name: Inspect conda environment
        shell: bash -el {0}
        run: |
            conda info
            conda list
      - name: Build package distribution files
        shell: bash -el {0}
        run: |
            python -c 'import shutil; [shutil.rmtree(p, True) for p in ("build", "dist", "docs/_build")]'
            python -c 'import pathlib, shutil; [shutil.rmtree(p, True) for p in pathlib.Path("src").glob("*.egg-info")]'
            pip install build
            python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
